### ISSUE TITLE
The matcher 'havingExactly' is listed as a availabe in WireMock 2.x but doesn't exist.

### ISSUE THREAD

**Issue by CoryBond** [wiremock/wiremock.org#146]
### Summary

As listed in https://wiremock.org/docs/request-matching/#matching-headerquery-parameter-containing-multiple-values there is supposedly a matcher in wiremock 2.x that can match multiple values in a query param. That matcher is "havingExactly." 

However after importing 2.35 (latest stable release & latest 2.x release) for my project I could not find the matcher. Looking at list of available matchers in the 2.35 tag of WireMock (https://github.com/wiremock/wiremock/blob/2.35.0/src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java) I do not see it available there. When comparing it to master (https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java) you can see the `havingExactly` matcher is available. 

This is likely an error in the documentation for 2.x. "havingExactly" is not a available matcher for 2.x but 3.x only.

**Comment by oleg-nenashev** [comment]
So a patch needs to be submitted against the https://github.com/wiremock/wiremock.org/tree/2.x branch
