### ISSUE TITLE
WireMock API Templates Library page uses old WireMock 2 images, update to WireMock 3

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock.org#155]
### Page

/docs/mock-api-templates/

### Details

We have just released WireMock 3, but the page uses the 2.35.0 docker images. It would be great to update the page, preferably using the `{{ site.wiremock_version }}` macro as other pages do

**Comment by Smartmind12** [comment]
Hey @oleg-nenashev I would like to work on this issue!
