### ISSUE TITLE
Docs pages are 404ing

### ISSUE THREAD

**Issue by aaron-goff** [wiremock/wiremock.org#159]
### Details

This is an incomplete list of documentation pages that are 404ing with the official change to WireMock 3.x.

- [Running Standalone](https://wiremock.org/docs/running-standalone/) -> exposed link is in [this section](https://wiremock.org/docs/download-and-installation/#download-options)
- [Download](https://wiremock.org/docs/download) -> exposed link is in [the top section](https://wiremock.org/docs/standalone/java-jar/)

Depending on how you want to tackle fixing these links, I can continue updating this as I find more 404s.

_Additionally_, the Test Engineer in me wants to get some verification tests that no links 404, but 🤷🏻 I know that's a whole other effort 😄

**Comment by oleg-nenashev** [comment]
The first one is fixed in https://github.com/wiremock/wiremock.org/pull/158

**Comment by oleg-nenashev** [comment]
Created https://github.com/wiremock/wiremock.org/issues/161 to actually make the link checker a part of the CI pipeline

**Comment by aaron-goff** [comment]
@oleg-nenashev Found another:
https://wiremock.org/docs/extending-wiremock/extensibility/custom-matching/, linked from https://wiremock.org/docs/extending-wiremock/#custom-request-matchers
(I think that's really just anything under `.../extensibility/*`)

**Comment by oleg-nenashev** [comment]
Yes, we had a regression somewhere, most likely when updating one of the components in the build process. My action item is to have a link checker enforced so that it doesn't happen again.
