### ISSUE TITLE
Simplify the Testcontainers Golang sample code

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock.org#170]
### Page

/docs/solutions/testcontainers/

### Details

We added a bunch of quality of life methods to Testcontainers Go module API, and now it is easier to use the module. The examnple is much shorter: https://github.com/wiremock/wiremock-testcontainers-go/blob/main/examples/quickstart/quickstart_test.go . It would be nice to update the solutions page accordingly

**Comment by Smartmind12** [comment]
Hey @oleg-nenashev I would like to work on this issue!
