### ISSUE TITLE
Issue on Download and Installation - Docker image references non-existent 3-digit tags

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock.org#171]
### Page

/docs/download-and-installation/

### Details

This is a regression after switching to 4-digit versions in the releases by default in WireMock Docker

![image](https://github.com/wiremock/wiremock.org/assets/3000480/705021d6-03fd-4425-aed8-0e866e45f69a)

**Comment by rajdip-b** [comment]
Hello! I would like to work on this bug. Can I be assigned this issue?

**Comment by oleg-nenashev** [comment]
@rajdip-b I updated the Docker Image release pipelines to actually produce these tabs, but it would be nice to have a proper solution here. So yeah, please feel free to submit a patch. Maybe adopting https://www.updatecli.io/ from @olblak in GitHub Actions would be a good solution

**Comment by olblak** [comment]
@oleg-nenashev Are you looking to automatically update https://github.com/wiremock/wiremock.org/blob/1e14ade03b5ec625f27a7c330263d8a4e5edcd2f/_config.yml#L237C1-L237C24 ? based on the latest Wiremock version retrieved from  https://github.com/wiremock/wiremock?

I could probably contribute an update pipeline if needed

**Comment by oleg-nenashev** [comment]
@olblak any patches would be welcome! Yes we use this repository as a source of the versions so it should be a quite trivial configuration in UpdateCLI . Have never got to it after the workaround

**Comment by olblak** [comment]
@oleg-nenashev pullrequest opened :)
