### ISSUE TITLE
outdated documentation for ResponseTemplateTransformer

### ISSUE THREAD

**Issue by jarekczek** [wiremock/wiremock.org#210]
### Summary

I am facing a task of upgrading from wiremock 2.26. I have problems with creating ResponseTemplateTransformer. Seems like the [Response Templating](https://wiremock.org/docs/response-templating/) section uses ResponseTemplateTransformer.Builder, which is now removed. Could you please document the way this transformer should be created?

**Comment by TomerPacific** [comment]
Hi @oleg-nenashev, I'd like to help out. How can I begin this task?

**Comment by oleg-nenashev** [comment]
@TomerPacific thanks for the interest. I would recommend exploring this functionality in WireMock 2 by following the existing docs, and then updating to WireMock 3 and fixing the documentation accordingly

**Comment by TomerPacific** [comment]
@oleg-nenashev - Can you provide some feedback regarding what I wrote above?

**Comment by oleg-nenashev** [comment]
Hi. Catching up with my backlog, will respond asap. Please note the better way to get more feedback is bringing it up in `#help-contributing` because there are more folks who can respond

**Comment by jarekczek** [comment]
In the example there is a method `getTemplateEngine()`. Where does it come from?

**Comment by Balaalwayz** [comment]
@jarekczek , did you find an answer. I see a defaultTemplateEngine() static method in TemplateEngine class.
