### ISSUE TITLE
Add Open Graph image support

### ISSUE THREAD

**Issue by iamrajiv** [wiremock/wiremock.org#83]
## Description

The Open Graph images for https://wiremock.org/ are not being generated when shared on social media.

<img width="633" alt="Screenshot 2023-05-09 at 10 50 03 AM" src="https://user-images.githubusercontent.com/42106787/237001118-35962f3b-463c-425f-b253-d3739ee7a5f3.png">

## References

To validate results, use https://metatags.io/.

**Comment by oleg-nenashev** [comment]
Duplicates https://github.com/wiremock/wiremock.org/issues/26 . I am waiting for the new logo vectors before it is actionable. See https://github.com/wiremock/community/issues/32
