### ISSUE TITLE
Improve icons in the menu navbar

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock.org#89]
### Proposal

As @tomakehurst mentioned in #82 , the vertical alignment and look and feel of the new icons could be better. I suggest looking for an open source icon set to use, and tinkering with CSS a bit.

![image](https://github.com/wiremock/wiremock.org/assets/3000480/8d327587-4577-4268-ad11-627e22c6aa7e)

### References

- #82

**Comment by shirsho-roy** [comment]
@oleg-nenashev  Can you assign me this issue, I would love to work on this.

**Comment by shirsho-roy** [comment]
Ok Sure

**Comment by shirsho-roy** [comment]
![WhatsApp Image 2023-05-20 at 2 48 38 PM](https://github.com/wiremock/wiremock.org/assets/105341321/e4b27c0c-cc94-4816-85ed-cb5919e1ea60)
I made some changes in the icons and overall alignment of all the items in navbar, @oleg-nenashev Could you please review if these looks fine or if there is need for further enhancements.

**Comment by oleg-nenashev** [comment]
They do not seem aligned w.r.t the style. Did you take a particular library? Which one?

**Comment by shirsho-roy** [comment]
I tried experimenting with heroicons library and some more. Few of them looked inconsistent so had to discard them. Let me check for some more icon set.

**Comment by shirsho-roy** [comment]
@oleg-nenashev did you refer to the icon alignment or nav-links alignment?

**Comment by oleg-nenashev** [comment]
Hello, I can review code but not the screenshots. It seems to be improving the situation, so please don't hesitate to send me the pull request

**Comment by shirsho-roy** [comment]
Sure I will

**Comment by shirsho-roy** [comment]
#107 
Sent the pull request for enhancement.
