### ISSUE TITLE
Documentation landing could render better on mobile devices

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock.org#95]
### Page

/docs/

### Details

Right now the layouts do not reduce the number of columns when on small devices. The `flex` layout should normally do that, but it seems I messed up something in the CSS. It would be great to apply a patch, likely a quick one

![image](https://github.com/wiremock/wiremock.org/assets/3000480/614dadb7-e020-4743-8c0c-1b56e4ddfdd0)

**Comment by shirsho-roy** [comment]
@oleg-nenashev  I would like to work on this issue, Could you please assign it to me?

**Comment by tecrade** [comment]
@oleg-nenashev Is this issue fixed. If not, could you please assign it to me?

**Comment by oleg-nenashev** [comment]
Please feel free to go ahead, there was no pull request from what I know

**Comment by bwnnwtt** [comment]
hi @oleg-nenashev, i've taken up this issue since it hasn't been fixed.

please refer to PR https://github.com/wiremock/wiremock.org/pull/175

**Comment by oleg-nenashev** [comment]
Thanks 👍
